version: '2'
services:
  rails: &app_base
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: "Dockerfile"
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app"
    volumes_from:
      - db_data
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  spring:
    <<: *app_base
    command: ["bundle", "exec", "spring", "server"]
    ports: []
    tty: false
    stdin_open: false
  db:
    build: ./sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes_from:
      - db_data
    ports:
      - "3333:3306"
  db_data:
    image: "busybox"
    volumes:
      - "db:/var/lib/mysql"
      - "bundle:/usr/local/bundle"

volumes:
  db:
    driver: local
  bundle:
    driver: local
